# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-21 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20191020_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Name',
            field=models.TextField(default=b'Any'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default=b'Welcome !'),
        ),
    ]
